# Generated by Django 5.1.5 on 2025-02-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_comment_author_alter_comment_listing_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="category",
        ),
        migrations.AddField(
            model_name="listing",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="categoryListing", to="auctions.category"
            ),
        ),
    ]
