# Generated by Django 5.1.5 on 2025-02-22 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_remove_listing_category_listing_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.ForeignKey(
                blank=True,
                default="0",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bidPrice",
                to="auctions.bid",
            ),
        ),
    ]
